### ISSUE TITLE
'Undefined is not a function' when reading an image (missing 'sgtest.decodeJpegBuffer')

### ISSUE THREAD

**Issue by almilo** [joshmarinacci/aminogfx#14]
After re-installing 'aminogfx-gl' (https://github.com/joshmarinacci/aminogfx/issues/10) under node 0.12 in a PI 2 with Raspbian Wheezy (libjpeg8-dev and libpng-dev are installed), and using some code from https://github.com/joshmarinacci/aminogfx/blob/master/demos/slideshow/slideshow.js I get:

TypeError: undefined is not a function
    at Object.gl_native.decodeJpegBuffer (/home/pi/amino/node_modules/aminogfx-gl/main.js:294:61)
    at Object.gl_native.loadImage (/home/pi/amino/node_modules/aminogfx-gl/main.js:288:40)
    at /home/pi/amino/node_modules/aminogfx-gl/node_modules/aminogfx/src/primitives.js:187:37
    at Array.<anonymous> (/home/pi/amino/node_modules/aminogfx-gl/node_modules/aminogfx/src/amino.js:31:13)
    at Function.prop.set (/home/pi/amino/node_modules/aminogfx-gl/node_modules/aminogfx/src/amino.js:42:30)
    at ImageView.prop [as src] (/home/pi/amino/node_modules/aminogfx-gl/node_modules/aminogfx/src/amino.js:16:25)
    at /home/pi/amino/slideshow.js:46:9
...

slideshow.js46:9 is     iv1.src(files.next());

Problem seems to be that 'sgtest.decodeJpegBuffer' binding does not exist. Any idea why?

Thanks,
Berto

**Comment by joshmarinacci** [comment]
I removed the native jpeg decode a while ago to reduce native dependencies. It should be using a pure js version now. Thanks bug implies there is somewhere else I need to update the code. I'll look at it tonight.

**Comment by almilo** [comment]
@joshmarinacci Many thanks!! Looking forward to it!

**Comment by joshmarinacci** [comment]
this is fixed now.
