### ISSUE TITLE
404 for aminonative 1.6.4 on npm install

### ISSUE THREAD

**Issue by F1LT3R** [joshmarinacci/aminogfx#19]
When I try to install your library, I get the following 404 errors. (See shell output below).

These resources that your node package is trying to download to not seem to be available on your site.

Is this project still active?

```shell
npm install aminogfx-gl

# > aminogfx-gl@1.6.4 install /Users/al/repos/aminogfx-test/node_modules/aminogfx-gl
# > node-pre-gyp install --fallback-to-build
# 
# node-pre-gyp ERR! Tried to download(404): https://joshondesign.com/p/apps/aminogfx/builds/aminonative-v1.6.4-node-v64-darwin-x64.tar.gz
# node-pre-gyp ERR! Pre-built binaries not found for aminogfx-gl@1.6.4 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
# node-pre-gyp ERR! Tried to download(undefined): https://joshondesign.com/p/apps/aminogfx/builds/aminonative-v1.6.4-node-v64-darwin-x64.tar.gz
# node-pre-gyp ERR! Pre-built binaries not found for aminogfx-gl@1.6.4 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
# Package glfw3 was not found in the pkg-config search path.
# Perhaps you should add the directory containing `glfw3.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'glfw3' found
# Package glfw3 was not found in the pkg-config search path.
# Perhaps you should add the directory containing `glfw3.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'glfw3' found
# gyp: Call to 'pkg-config --libs glfw3' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
# gyp: Call to 'pkg-config --libs glfw3' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
# gypgyp  ERR!ERR!  configure errorconfigure error
# 
# gyp gypERR! stack  Error: `gyp` failed with exit code: 1
# gypERR! ERR!  stackstack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
# gyp Error: `gyp` failed with exit code: 1
#  gypERR!  stack     at ChildProcess.emit (events.js:182:13)
# ERR!gyp  ERR!stack stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
#      at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
# gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
# gypgyp  ERR!ERR!  Systemstack Darwin 17.4.0
#      at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
# gyp ERR! gypcommand  "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding/aminonative.node" "--module_name=aminonative" "--module_path=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding"
# ERR! gypSystem  Darwin 17.4.0
# ERR! cwd /Users/al/repos/aminogfx-test/node_modules/aminogfx-gl
# gypgyp  ERR!ERR!  commandnode -v v10.8.0
#  "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding/aminonative.node" "--module_name=aminonative" "--module_path=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding"
# gypgyp  ERR! ERR!node-gyp -v  v3.7.0
# cwd /Users/al/repos/aminogfx-test/node_modules/aminogfx-gl
# gypgyp  ERR!ERR!  not oknode -v
#  v10.8.0
# gyp ERR! node-gyp -v v3.7.0
# gyp ERR! not ok
# node-pre-gyp ERR! build error
# node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding/aminonative.node --module_name=aminonative --module_path=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding' (1)
# node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/al/repos/aminogfx-test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
# node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
# node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
# node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
# node-pre-gyp ERR! System Darwin 17.4.0
# node-pre-gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/Users/al/repos/aminogfx-test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
# node-pre-gyp ERR! cwd /Users/al/repos/aminogfx-test/node_modules/aminogfx-gl
# node-pre-gyp ERR! node -v v10.8.0
# node-pre-gyp ERR! node-pre-gyp -v v0.6.39
# node-pre-gyp ERR! not ok
# Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding/aminonative.node --module_name=aminonative --module_path=/Users/al/repos/aminogfx-test/node_modules/aminogfx-gl/build/binding' (1)
# npm WARN aminogfx-test@1.0.0 No description
# npm WARN aminogfx-test@1.0.0 No repository field.
# 
# npm ERR! code ELIFECYCLE
# npm ERR! errno 1
# npm ERR! aminogfx-gl@1.6.4 install: `node-pre-gyp install --fallback-to-build`
# npm ERR! Exit status 1
# npm ERR!
# npm ERR! Failed at the aminogfx-gl@1.6.4 install script.
# npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
# 
# npm ERR! A complete log of this run can be found in:
# npm ERR!     /Users/al/.npm/_logs/2018-08-13T02_04_03_895Z-debug.log#
```

**Comment by joshmarinacci** [comment]
The project is not under active development but it should still work. The error indicates it tried to build the native parts by hand and couldn't find the glfw3 library. What system are you building on? Mac?

**Comment by F1LT3R** [comment]
Yeah, Mac. I'll probably pass if this is not active though. Thanks for taking the time to respond.

**Comment by joshmarinacci** [comment]
While we aren't active it should work just fine.  The requirement is that you don't have glfw3 installed, which is required whether or not you are building from source or not. You'll need to install that first using something like HomeBrew.
